import os

SECRET_KEY = 'so-secret'


# YELP API
YELP_API_KEY = 'ZguS6o0l5AgSmmZMgnI4nQ'
YELP_CONSUMER_SECRET = '0StXfVCVhDqQqvfiMPuwBJJs6Ws'
YELP_TOKEN = 'L9XUrmpuzh92lMR5T2u19h-YmfpQaTvX'
YELP_TOCKEN_SECRET = '0zR8alYYU-p_sn1aXbSZke16M24'

# GOOGLE API
GOOGLE_API_KEY = 'AIzaSyDt69MaVC9IlGIfht0L4Ho8vdLsvDlwsh8'
